name: "retail_application"
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^1.1.6
  phonecodes: ^0.0.4
  country_flags: ^3.0.0
  video_player: ^2.7.0 
  local_auth: ^2.3.0
  shared_preferences: ^2.1.0
  carousel_slider: ^5.1.1
  fl_chart: ^0.69.0

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  go_router: ^10.0.0
  dio: ^5.4.1
  http: ^1.2.2 
  rename: ^3.1.0
  calendar_date_picker2: ^1.0.0
  intl: ^0.20.2
  gradient_borders: ^1.0.2
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/Icon.png

flutter:
  assets:
    - assets/images/
    - assets/mock/
    - assets/alerts/
    - mock/
    - mock/products/
    - mock/Dashboard/
    - mock/mock_datas/
    - mock/Notifications/
    - mock/menu_options/
    - mock/login/
    - assets/loader/
    - assets/login/
    - assets/promotions/
    - assets/accountdashboard/


  uses-material-design: true
  generate: true
