name: apz_crypto
description: "Dart plugin which helps in Cryptography."
version: 1.0.0
homepage:

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.6.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
